### ISSUE TITLE
Needs to be updated for compatibility with league/container 2x?

### ISSUE THREAD

**Issue by bradhanebury** [thephpleague/tactician-container#7]

**Comment by rosstuck** [comment]
Sorry about this, I haven't had a chance to look at this or if League\Container 2.0 has landed yet. If you'd like to provide a PR or some details about what I need to change, I'd be glad to review?

Alternately, I'm recommending folks use the standard CallableListener that ships with Tactician core, rather than an individual adapter for every container out there. https://github.com/thephpleague/tactician/blob/master/src/Handler/Locator/CallableLocator.php

**Comment by jonbernardi** [comment]
Take a look at pull request #6 I submitted a while back for upgrading to League\Container 2.0 (which has a stable release now).

Because League\Container 2.x implements [container-interop/container-interop](https://github.com/container-interop/container-interop) upgrading will allow this package to work with any container that also implements the container-interop interface rather than just the league/container package.

**Comment by rosstuck** [comment]
See #8 for a status update but dev-master should work for now. Sorry for the long delay on this!
